In [18]:
import pandas_datareader.data as web
import datetime

In [36]:
start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2016, 12, 31)
df = web.DataReader('AMZN', 'morningstar', start, end)

In [37]:
print(df)

                     Close      High      Low    Open    Volume
Symbol Date
AMZN   2010-01-01  134.520  137.2800  134.520  137.08         0
       2010-01-04  133.900  136.6100  133.140  136.28   7600543
       2010-01-05  134.690  135.4790  131.810  133.25   8856456
       2010-01-06  132.250  134.7300  131.650  134.63   7180977
       2010-01-07  130.000  132.3200  128.800  131.96  11030124
       2010-01-08  133.520  133.6800  129.030  130.70   9833829
       2010-01-11  130.308  132.8000  129.210  132.73   8786668
       2010-01-12  127.350  129.8200  126.550  129.06   9098190
       2010-01-13  129.110  129.7100  125.750  128.07  10727856
       2010-01-14  127.350  130.3800  126.400  129.18   9788435
       2010-01-15  127.140  129.6500  127.060  129.35  15382763
       2010-01-18  127.140  129.6500  127.060  129.35         0
       2010-01-19  127.610  128.0000  124.330  126.20   8900116
       2010-01-20  125.780  129.2000  125.080  127.18   9081533
       2010-01-21  126.620  128.1500  125.000  127.27   9976146
       2010-01-22  121.430  127.6700  120.760  125.60  11577818
       2010-01-25  120.310  122.2800  118.120  122.03  12031053
       2010-01-26  119.480  122.9800  119.061  120.05   9567607
       2010-01-27  122.750  123.3300  118.800  120.99  14765273
       2010-01-28  126.030  127.2000  122.800  124.46  27293062
       2010-01-29  125.410  131.8499  124.140  129.74  29478976
       2010-02-01  118.870  124.8600  113.820  123.22  37774317
       2010-02-02  118.120  118.9800  114.400  118.86  23084986
       2010-02-03  119.100  119.6100  116.560  117.09  12409012
       2010-02-04  115.940  120.3300  115.740  118.61  12783912
       2010-02-05  117.390  117.6500  114.100  115.85  11027086
       2010-02-08  116.830  121.0000  116.560  119.64   9898391
       2010-02-09  118.030  119.0900  117.000  118.29   9227158
       2010-02-10  117.360  118.6100  116.000  117.88   6236250
       2010-02-11  120.090  120.4201  116.500  117.22   8344469
...                    ...       ...      ...     ...       ...
       2016-11-21  780.000  780.3500  765.110  766.00   4614574
       2016-11-22  785.330  792.4000  781.000  788.17   5311320
       2016-11-23  780.120  781.7500  773.120  781.73   3540263
       2016-11-24  780.120  780.1200  780.120  780.12         0
       2016-11-25  780.370  786.7500  777.900  786.50   1837068
       2016-11-28  766.770  777.0000  764.240  776.99   4438828
       2016-11-29  762.520  769.8900  761.320  768.00   3272344
       2016-11-30  750.570  768.0900  750.250  762.00   4625946
       2016-12-01  743.650  753.3700  738.030  752.41   4665993
       2016-12-02  740.340  748.4903  736.700  743.40   3561307
       2016-12-05  759.360  761.4900  742.000  745.00   4314723
       2016-12-06  764.720  768.2400  757.250  763.99   3794746
       2016-12-07  770.420  770.4200  755.820  764.55   3684906
       2016-12-08  767.330  773.7900  765.190  771.87   3189608
       2016-12-09  768.660  770.2500  765.340  770.00   2470923
       2016-12-12  760.120  766.8900  757.200  766.40   2963945
       2016-12-13  774.340  782.4600  762.000  764.96   5285288
       2016-12-14  768.820  780.8600  762.810  778.25   5454836
       2016-12-15  761.000  769.1000  760.310  766.28   3801927
       2016-12-16  757.770  765.1300  754.000  765.00   4848219
       2016-12-19  766.000  770.5000  756.160  758.89   3113240
       2016-12-20  771.220  774.3900  767.710  768.65   2703629
       2016-12-21  770.600  771.2200  765.700  770.00   2044629
       2016-12-22  766.340  771.2100  763.020  768.12   2543551
       2016-12-23  760.590  766.5000  757.990  764.55   1981616
       2016-12-26  760.590  760.5900  760.590  760.59         0
       2016-12-27  771.400  774.6500  761.200  763.40   2638725
       2016-12-28  772.130  780.0000  770.500  776.25   3301025
       2016-12-29  765.150  773.4000  760.850  772.40   3158299
       2016-12-30  749.870  767.3999  748.280  766.47   4139449

[1826 rows x 5 columns]